#!/usr/bin/env php
<?php
declare(strict_types=1);

try {
    $default_host = '127.0.0.1';
    $default_port = '80';
    $host = $argv[1] ?? $default_host . ':' . $default_port;

    if (preg_match('/^localhost:(.*)$/', $host, $port)) {
        $host = $default_host . ':' . $port[1];
    }

    exec(sprintf('php -S %s -t ./public', $host));
} catch (Throwable $exception){
    $exception->getMessage();
}
